package dds.tp.carbono.http.utils;

public enum Uri { 
    ROOT, 
    LOGIN, 
    REGISTER, 
    ADMIN, 
    ADMIN_ORG, 
    MEMBER,
    MEMBER_TRAYECTOS, 
    MEMBER_TRAYECTOS_AUTOCOMPLETE,
    MEMBER_POINTS,
    MEMBER_POINTS_AUTOCOMPLETE,
    ORG, 
    ORG_METRICS, 
    ADMIN_FACTOR_EMISION, 
    AGENTE_SECTORIAL,
    AGENTE_SECTORIAL_HUELLA
}
